name: Visualizations by Eric Johnson
favicon: null
layout_spectrum: 0.99658
typography_spectrum: 0.5014306623488665
title: Visualizations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f0308'
    - '#033052'
    - '#ae3e12'
    - '#1eb5f0'
    - '#dbaf60'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
