name: Visualizations by Eric Johnson
favicon: null
layout_spectrum: 0.00245
typography_spectrum: 0.50102
title: Visualizations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#1fc3ba'
    - '#9e7159'
    - '#64300f'
    - '#085840'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
